import type { Metadata } from "next";
import { Lato, Space_Mono , Jura } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux"
import { store } from "./store";
import Providers from './providers'


const lato = Lato({
  weight: ["400","100","300","700","900"],
    // fix: provide weights as array
  variable: "--font-lato", // fix: matches Dashboard usage
  subsets: ["latin"],
});

const jura = Jura({
  weight: ["400", "300" , "500", "600", "700"],
    // fix: provide weights as array
  variable: "--font-jura", // fix: matches Dashboard usage
  subsets: ["latin"],
});
const spaceMono = Space_Mono({
  weight: ["400", "700"], // fix: provide weights as array
  variable: "--font-space-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

 

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${lato.variable} ${spaceMono.variable} ${jura.variable} antialiased`}>
        <Providers>
           
            {children}
        
        </Providers>
      </body>
    </html>
  )
}
